import json, csv
from pathlib import Path
from collections import Counter

# (id, question, expected_provision, divergence_type, foreign_default)
# foreign_default: dict or None. None = STILL NEEDS SOURCING before M3 can run.
ITEMS = [
 # ---------- Part VII: takedown / service providers (15) : STRUCTURAL ----------
 ("NCB-C-001","Under Nigerian law, my song was uploaded to a Lagos-based streaming platform without my permission. What must I actually put in the notice I send them?","54(2)","structural",{"US": "17 USC 512(c)(3)(A): six elements - signature, identification of work, identification of material, contact info, good-faith statement, and a statement that the notice is accurate and UNDER PENALTY OF PERJURY that the sender is authorised", "UK": "CDPA has no statutory notice-and-takedown contents provision; liability limits derive from the Electronic Commerce (EC Directive) Regulations 2002"}),
 ("NCB-C-002","Under Nigerian law, when I send a takedown notice about my film, which part of what I say has to be sworn - my belief that the use is unauthorised, or my authority to act for the owner?","54(2)(e)+54(2)(f)","structural",{"US": "17 USC 512(c)(3)(A): the PENALTY OF PERJURY attaches ONLY to the statement that the complaining party is AUTHORISED TO ACT on behalf of the owner (clause vi). The good-faith belief that the use is unauthorised (clause v) is a SEPARATE, UNSWORN statement.", "UK": "CDPA 1988 contains no statutory notice-and-takedown regime; no equivalent sworn-statement requirement.", "note": "Nigeria s.54(2)(e) puts the BELIEF THAT THE USE IS UNAUTHORISED on oath, and s.54(2)(f) makes the accuracy/authority statement unsworn. The US swears the opposite element. Divergence is in WHAT is sworn, not whether."}),
 ("NCB-C-003","Under Nigerian law, someone knowingly filed a false takedown claim against my YouTube channel and my video was pulled. Do I have any remedy against them?","57","structural",{"US": "17 USC 512(f): a person who KNOWINGLY MATERIALLY MISREPRESENTS that material is infringing, or was removed by mistake, is liable for damages INCLUDING COSTS AND ATTORNEYS' FEES incurred by the alleged infringer, ANY copyright owner or licensee, OR THE SERVICE PROVIDER injured by the misrepresentation. Nigeria s.57 gives damages only to 'the person' injured by the provider's reliance - narrower class, no costs or fees.", "UK": "CDPA 1988 contains no notice-and-takedown or safe-harbour regime; UK intermediary liability limits derive from the Electronic Commerce (EC Directive) Regulations 2002, regs 17-19, which are outside the Act."}),
 ("NCB-C-004","Under Nigerian law, a Nigerian platform has received my takedown notice about a pirated film. What steps must it take, and who must it tell?","55(1)","structural",{"US": "17 USC 512(c)(1)(C),(g)(2)(A): expeditious removal on notice plus reasonable steps to notify the subscriber; no statutory ORDER of steps", "UK": "no equivalent statutory sequence in CDPA"}),
 ("NCB-C-005","Under Nigerian law, the person who uploaded my track sent the platform a counter-notice. How long do I have to reply before they can put it back up?","55(2)(b)","structural",
    {"US":"provider must restore the material not less than 10 nor more than 14 BUSINESS days after the counter notice, unless the rightsholder has FILED A COURT ACTION to restrain the subscriber (17 U.S.C. 512(g)(2)(B)-(C))"}),
 ("NCB-C-006","Under Nigerian law, a platform removed my pirated album but the same file was uploaded again a week later. Does the platform have any duty to stop that happening?","55(3)","structural",{"US": "17 USC 512(g)(2)(B)-(C): provider restores in 10-14 BUSINESS days unless the rightsholder FILES A COURT ACTION to restrain the subscriber", "UK": "no statutory counter-notice regime in CDPA"}),
 ("NCB-C-007","Under Nigerian law, I am unhappy with how a Nigerian platform handled my copyright complaint. Is going to court my only option?","55(4)","structural",{"US": "17 USC 512(m)(1) EXPRESSLY DISCLAIMS any monitoring duty: safe harbour is not conditioned on 'a service provider monitoring its service or affirmatively seeking facts indicating infringing activity'. NO stay-down obligation. Nigeria s.55(3) requires the OPPOSITE - effective steps in accordance with high industry standards to prevent reloading, and removal of reloaded content without further notice. DIRECTLY OPPOSED POSITIONS.", "UK": "CDPA 1988 contains no notice-and-takedown or safe-harbour regime; UK intermediary liability limits derive from the Electronic Commerce (EC Directive) Regulations 2002, regs 17-19, which are outside the Act."}),
 ("NCB-C-008","Under Nigerian law, a Nigerian hosting company received my takedown notice three months ago and has done nothing. What is the company exposed to?","55(6)","structural",{"US": "17 USC 512 provides no administrative determination route; 512(h) subpoenas and 512(j) injunctions both go through a court. Nigeria s.55(4) allows referral to the Commission for determination.", "UK": "CDPA 1988 contains no notice-and-takedown or safe-harbour regime; UK intermediary liability limits derive from the Electronic Commerce (EC Directive) Regulations 2002, regs 17-19, which are outside the Act."}),
 ("NCB-C-009","Under Nigerian law, a user keeps re-uploading my films to a Nigerian platform and I have reported it repeatedly. At what point must the platform suspend that account?","56(1)(b)","structural",{"US": "17 USC 512(c)(1): a non-complying provider simply loses the safe harbour and faces ordinary secondary-liability analysis. Nigeria s.55(6) deems non-compliance a BREACH OF STATUTORY DUTY and makes the provider liable for the infringement to the SAME EXTENT as the person who posted the content.", "UK": "CDPA 1988 contains no notice-and-takedown or safe-harbour regime; UK intermediary liability limits derive from the Electronic Commerce (EC Directive) Regulations 2002, regs 17-19, which are outside the Act."}),
 ("NCB-C-010","Under Nigerian law, my account on a Nigerian platform was suspended over copyright complaints I believe were about someone else. How long do I have to object, and who decides?","56(2)","structural",{"US": "17 USC 512(g)(3): counter notification must include signature, identification of removed material, a penalty-of-perjury statement of mistake/misidentification, contact details, AND consent to federal district court jurisdiction plus agreement to accept service", "UK": "no equivalent"}),
 ("NCB-C-011","Under Nigerian law, a Nigerian platform suspended a repeat infringer account. Is there a minimum period the suspension must run?","56(1)(b)","structural",{"US": "17 USC 512(i)(1)(A) requires only a 'policy that provides for the termination in appropriate circumstances' of repeat infringers - NO specified number of notifications. Nigeria s.56(1)(b) requires suspension after a SECOND notification on the same account.", "UK": "CDPA 1988 contains no notice-and-takedown or safe-harbour regime; UK intermediary liability limits derive from the Electronic Commerce (EC Directive) Regulations 2002, regs 17-19, which are outside the Act."}),
 ("NCB-C-012","Under Nigerian law, I run a Nigerian file-hosting service and users upload material I never review. What must I do to avoid being liable for infringing uploads?","58","structural",{"US": "17 USC 512(i)(1)(A): no minimum suspension period; termination 'in appropriate circumstances' only. Nigeria s.56(1)(b) sets a minimum of ONE MONTH.", "UK": "CDPA 1988 contains no notice-and-takedown or safe-harbour regime; UK intermediary liability limits derive from the Electronic Commerce (EC Directive) Regulations 2002, regs 17-19, which are outside the Act."}),
 ("NCB-C-013","Under Nigerian law, my Nigerian website only lists links to other sites, some of which turn out to host pirated films. Am I liable simply for linking?","59","structural",{"US": "17 USC 512(c)(1): no actual knowledge or awareness of apparent infringing activity, no direct financial benefit where the provider has the right and ability to control, expeditious removal on notice; plus 512(c)(2) designated agent, 512(i) repeat-infringer policy and standard technical measures. Nigeria s.58 mirrors the knowledge and financial-benefit conditions but adds compliance with the s.56 suspension procedure.", "UK": "CDPA 1988 contains no notice-and-takedown or safe-harbour regime; UK intermediary liability limits derive from the Electronic Commerce (EC Directive) Regulations 2002, regs 17-19, which are outside the Act."}),
 ("NCB-C-014","Under Nigerian law, I run a Nigerian social platform. Is there anything I must publish on my website before I can rely on the liability protections?","62(1)(b)(ii)","structural",{"US": "17 USC 512(c)(2): agent must be designated on the website AND registered with the U.S. Copyright Office, which maintains a public directory", "UK": "no equivalent registration requirement"}),
 ("NCB-C-015","Under Nigerian law, a website is distributing pirated Nollywood films. Can it be blocked without anyone going to court first?","61","no_analogue",{"US": "No administrative blocking power in 17 USC. 512(j) permits INJUNCTIONS only, granted by a COURT, constrained to the least burdensome comparably effective relief (512(j)(2)(D)) and available only after notice to the provider and an opportunity to appear (512(j)(3)).", "UK": "CDPA 1988 s.97A(1): 'The High Court (in Scotland, the Court of Session) shall have power to grant an injunction against a service provider, where that service provider has actual knowledge of another person using their service to infringe copyright.' JUDICIAL, not administrative. VERIFIED against CDPA text.", "note": "BOTH comparators require a COURT. Nigeria s.61 empowers the Commission to block or disable access DIRECTLY, notwithstanding any other law, on its own reasonable belief. No-analogue against US and UK alike."}),

 # ---------- Folklore (8) + levy (4) : NO-ANALOGUE ----------
 ("NCB-C-016","Under Nigerian law, my band sampled a traditional Yoruba folk song on a track we are releasing commercially. Do we need anyone's permission?","74(1)+74(4)","no_analogue",{"US": "No provision found in 17 USC on search for 'folklore', 'traditional', 'expressions of folklore'. US federal copyright has no sui generis folklore protection; folk material generally falls in the public domain unless a specific fixed arrangement attracts ordinary copyright.", "UK": "CDPA 1988 s.169 'Folklore, &c.: anonymous unpublished works' is NOT a sui generis folklore right. It creates a PRESUMPTION that the author of an unpublished work of unknown authorship qualified for copyright, and empowers Her Majesty by Order in Council to DESIGNATE A FOREIGN BODY appointed under another country's law to protect such works (s.169(2)-(3)). It is the RECEIVING END of a regime like Nigeria's, not an equivalent to it."}),
 ("NCB-C-017","Under Nigerian law, if permission is needed to use a Nigerian folk song commercially, who grants it - the community it came from, or some other body?","74(4)","no_analogue",{"US": "No provision found in 17 USC on search for 'folklore', 'traditional', 'expressions of folklore'. US federal copyright has no sui generis folklore protection; folk material generally falls in the public domain unless a specific fixed arrangement attracts ordinary copyright.", "UK": "CDPA 1988 s.169 'Folklore, &c.: anonymous unpublished works' is NOT a sui generis folklore right. It creates a PRESUMPTION that the author of an unpublished work of unknown authorship qualified for copyright, and empowers Her Majesty by Order in Council to DESIGNATE A FOREIGN BODY appointed under another country's law to protect such works (s.169(2)-(3)). It is the RECEIVING END of a regime like Nigeria's, not an equivalent to it."}),
 ("NCB-C-018","Under Nigerian law, does protection for traditional folk expressions ever expire, the way copyright in a book does?","74","no_analogue",{"US": "No provision found in 17 USC on search for 'folklore', 'traditional', 'expressions of folklore'. US federal copyright has no sui generis folklore protection; folk material generally falls in the public domain unless a specific fixed arrangement attracts ordinary copyright.", "UK": "CDPA 1988 s.169 'Folklore, &c.: anonymous unpublished works' is NOT a sui generis folklore right. It creates a PRESUMPTION that the author of an unpublished work of unknown authorship qualified for copyright, and empowers Her Majesty by Order in Council to DESIGNATE A FOREIGN BODY appointed under another country's law to protect such works (s.169(2)-(3)). It is the RECEIVING END of a regime like Nigeria's, not an equivalent to it."}),
 ("NCB-C-019","Under Nigerian law, a lecturer at a Nigerian university used traditional folk riddles in a classroom lesson. Was permission required?","74(2)(b)","no_analogue",{"US": "No provision found in 17 USC on search for 'folklore', 'traditional', 'expressions of folklore'. US federal copyright has no sui generis folklore protection; folk material generally falls in the public domain unless a specific fixed arrangement attracts ordinary copyright.", "UK": "CDPA 1988 s.169 'Folklore, &c.: anonymous unpublished works' is NOT a sui generis folklore right. It creates a PRESUMPTION that the author of an unpublished work of unknown authorship qualified for copyright, and empowers Her Majesty by Order in Council to DESIGNATE A FOREIGN BODY appointed under another country's law to protect such works (s.169(2)-(3)). It is the RECEIVING END of a regime like Nigeria's, not an equivalent to it."}),
 ("NCB-C-020","Under Nigerian law, a novelist took motifs from Igbo folk tales and wrote an original novel around them. Is that permitted?","74(2)(d)","no_analogue",{"US": "No provision found in 17 USC on search for 'folklore', 'traditional', 'expressions of folklore'. US federal copyright has no sui generis folklore protection; folk material generally falls in the public domain unless a specific fixed arrangement attracts ordinary copyright.", "UK": "CDPA 1988 s.169 'Folklore, &c.: anonymous unpublished works' is NOT a sui generis folklore right. It creates a PRESUMPTION that the author of an unpublished work of unknown authorship qualified for copyright, and empowers Her Majesty by Order in Council to DESIGNATE A FOREIGN BODY appointed under another country's law to protect such works (s.169(2)-(3)). It is the RECEIVING END of a regime like Nigeria's, not an equivalent to it."}),
 ("NCB-C-021","Under Nigerian law, I am publishing a book that quotes a traditional folk song. Is there anything I am required to state about its origin?","74(3)","no_analogue",{"US": "No provision found in 17 USC on search for 'folklore', 'traditional', 'expressions of folklore'. US federal copyright has no sui generis folklore protection; folk material generally falls in the public domain unless a specific fixed arrangement attracts ordinary copyright.", "UK": "CDPA 1988 s.169 'Folklore, &c.: anonymous unpublished works' is NOT a sui generis folklore right. It creates a PRESUMPTION that the author of an unpublished work of unknown authorship qualified for copyright, and empowers Her Majesty by Order in Council to DESIGNATE A FOREIGN BODY appointed under another country's law to protect such works (s.169(2)-(3)). It is the RECEIVING END of a regime like Nigeria's, not an equivalent to it."}),
 ("NCB-C-022","Under Nigerian law, are traditional Nigerian textile patterns and wood carvings covered by any protection?","74(5)(d)","no_analogue",{"US": "No provision found in 17 USC on search for 'folklore', 'traditional', 'expressions of folklore'. US federal copyright has no sui generis folklore protection; folk material generally falls in the public domain unless a specific fixed arrangement attracts ordinary copyright.", "UK": "CDPA 1988 s.169 'Folklore, &c.: anonymous unpublished works' is NOT a sui generis folklore right. It creates a PRESUMPTION that the author of an unpublished work of unknown authorship qualified for copyright, and empowers Her Majesty by Order in Council to DESIGNATE A FOREIGN BODY appointed under another country's law to protect such works (s.169(2)-(3)). It is the RECEIVING END of a regime like Nigeria's, not an equivalent to it."}),
 ("NCB-C-023","Under Nigerian law, a Nollywood production filmed a traditional folk dance for a commercial feature without asking anyone. Is folk dance covered?","74(5)(c)","no_analogue",{"US": "No provision found in 17 USC on search for 'folklore', 'traditional', 'expressions of folklore'. US federal copyright has no sui generis folklore protection; folk material generally falls in the public domain unless a specific fixed arrangement attracts ordinary copyright.", "UK": "CDPA 1988 s.169 'Folklore, &c.: anonymous unpublished works' is NOT a sui generis folklore right. It creates a PRESUMPTION that the author of an unpublished work of unknown authorship qualified for copyright, and empowers Her Majesty by Order in Council to DESIGNATE A FOREIGN BODY appointed under another country's law to protect such works (s.169(2)-(3)). It is the RECEIVING END of a regime like Nigeria's, not an equivalent to it."}),
 ("NCB-C-024","Under Nigerian law, I import blank discs and duplicating equipment for my Lagos business. Is any levy payable on them?","89(1)","no_analogue",{"US": "17 USC ch.10 (Audio Home Recording Act) imposes royalties ONLY on 'digital audio recording devices/media' - defined at 1001(3)-(4) as devices whose digital recording function is designed or marketed PRIMARILY for making digital audio copies for private use. EXPRESSLY EXCLUDES professional models, dictation machines, and media primarily used for copying motion pictures, audiovisual works, or non-musical literary works including computer programs and databases. There is NO general levy on equipment capable of infringing copyright.", "UK": "No provision found in CDPA 1988 on search for 'levy', 'blank media' or 'private copying'. The UK has NO private copying levy; the 2014 private copying exception was introduced without a compensation scheme and was quashed in 2015."}),
 ("NCB-C-025","Under Nigerian law, who sets the amount of the copyright levy, and by what instrument?","89(2)","no_analogue",{"US": "17 USC ch.10 (Audio Home Recording Act) imposes royalties ONLY on 'digital audio recording devices/media' - defined at 1001(3)-(4) as devices whose digital recording function is designed or marketed PRIMARILY for making digital audio copies for private use. EXPRESSLY EXCLUDES professional models, dictation machines, and media primarily used for copying motion pictures, audiovisual works, or non-musical literary works including computer programs and databases. There is NO general levy on equipment capable of infringing copyright.", "UK": "No provision found in CDPA 1988 on search for 'levy', 'blank media' or 'private copying'. The UK has NO private copying levy; the 2014 private copying exception was introduced without a compensation scheme and was quashed in 2015."}),
 ("NCB-C-026","Under Nigerian law, once the copyright levy is collected, where does the money go and who can receive it?","89(3)","no_analogue",{"US": "17 USC ch.10 (Audio Home Recording Act) imposes royalties ONLY on 'digital audio recording devices/media' - defined at 1001(3)-(4) as devices whose digital recording function is designed or marketed PRIMARILY for making digital audio copies for private use. EXPRESSLY EXCLUDES professional models, dictation machines, and media primarily used for copying motion pictures, audiovisual works, or non-musical literary works including computer programs and databases. There is NO general levy on equipment capable of infringing copyright.", "UK": "No provision found in CDPA 1988 on search for 'levy', 'blank media' or 'private copying'. The UK has NO private copying levy; the 2014 private copying exception was introduced without a compensation scheme and was quashed in 2015."}),
 ("NCB-C-027","Under Nigerian law, does the copyright levy reach digital and electronic systems, or only physical items like blank discs?","89(5)","no_analogue",{"US": "17 USC ch.10 (Audio Home Recording Act) imposes royalties ONLY on 'digital audio recording devices/media' - defined at 1001(3)-(4) as devices whose digital recording function is designed or marketed PRIMARILY for making digital audio copies for private use. EXPRESSLY EXCLUDES professional models, dictation machines, and media primarily used for copying motion pictures, audiovisual works, or non-musical literary works including computer programs and databases. There is NO general levy on equipment capable of infringing copyright.", "UK": "No provision found in CDPA 1988 on search for 'levy', 'blank media' or 'private copying'. The UK has NO private copying levy; the 2014 private copying exception was introduced without a compensation scheme and was quashed in 2015."}),

 # ---------- Exceptions ss.21-26 (18) : SUBSTITUTIVE ----------
 ("NCB-C-028","Under Nigerian law, a teacher at a Lagos secondary school used the school photocopier to copy textbook pages for her class. Was that permitted?","21(1)","substitutive",
    {"US":"no equivalent categorical bar on reprographic copying; classroom copying is assessed under the open-ended fair use factors (17 U.S.C. 107)"}),
 ("NCB-C-029","Under Nigerian law, a lecturer wrote out a passage from a published poem on the whiteboard while teaching. Did that infringe?","21(1)","substitutive",{"US": "17 USC 107 expressly lists 'teaching (including multiple copies for classroom use)' as a fair use purpose; there is NO categorical bar on reprographic copying. Nigeria s.21(1) excludes exactly that method."}),
 ("NCB-C-030","Under Nigerian law, a private tutorial centre in Abuja that operates for profit copied part of a film to use in a lesson. Can it rely on the teaching exception?","21(2)","substitutive",{"US": "17 USC 107(1) treats 'nonprofit educational purposes' as ONE FACTOR in an open balance, not a threshold requirement. Nigeria s.21(2) restricts the audiovisual/sound-recording exception to non-profit educational institutions."}),
 ("NCB-C-031","Under Nigerian law, an examiner reproduced several lines of a published poem inside an examination paper. Was the poet's permission needed?","21(3)","substitutive",{"US": "17 USC 107 has no dedicated examination provision; examination use is assessed under the general fair use factors. Nigeria s.21(3) provides an express exception for setting, communicating or answering examination questions."}),
 ("NCB-C-032","Under Nigerian law, a Nigerian polytechnic recorded a television documentary off air to show in class. Was that allowed?","22(1)","substitutive",{"US": "17 USC 107 expressly lists 'teaching (including multiple copies for classroom use)' as a fair use purpose; NO categorical bar on reprographic copying", "UK": "CDPA s.36(1) permits copying extracts by educational establishments for non-commercial instruction, including reprographic copying, subject to the 5% cap"}),
 ("NCB-C-033","Under Nigerian law, a Nigerian school records television programmes for teaching. A licensing body now offers a scheme covering exactly that. Does the school still have a free hand?","22(2)","substitutive",{"US": "17 USC 107(1) treats 'nonprofit educational purposes' as ONE FACTOR in an open balance, not a threshold", "UK": "CDPA s.36(1)(a) requires the purpose be NON-COMMERCIAL - closer to Nigeria than the US is"}),
 ("NCB-C-034","Under Nigerian law, a Nigerian university wants to photocopy from a published textbook for teaching. How much may it copy, and how often?","23(2)","substitutive",
    {"US":"no fixed statutory percentage; extent of copying is one of four fair use factors (17 U.S.C. 107(3)) with no bright-line limit"}),
 ("NCB-C-035","Under Nigerian law, a publisher's licence agreement tells our Nigerian college we may copy no more than two per cent of any book. Is that term enforceable against us?","23(4)","substitutive",{"US": "17 USC 107(3) makes 'the amount and substantiality of the portion used' an open-ended factor with NO statutory percentage or time window. Nigeria s.23(2) sets a hard cap of five per cent in three months."}),
 ("NCB-C-036","Under Nigerian law, our Nigerian university already pays an annual licence fee to a copyright body for photocopying. Does that change what we may copy without permission?","23(3)","substitutive",{"US": "No 17 USC equivalent: US law contains no provision voiding contractual terms that restrict copying below the statutory allowance; licence terms generally govern. Nigeria s.23(4) makes such a term of no effect."}),
 ("NCB-C-037","Under Nigerian law, a student at a Lagos university sold me photocopied course material his department had produced for teaching. Is the copy I bought a lawful one?","24(1)","substitutive",{"US": "17 USC 107 has no dedicated examination provision; assessed under the general factors", "UK": "CDPA s.32 provides an express exception for examination purposes"}),
 ("NCB-C-038","Under Nigerian law, someone gave false information on a request form to obtain a copy of a work from a Nigerian library. Who bears the liability?","24(2)","substitutive",{"US": "17 USC 107(3) makes amount/substantiality an open factor with NO percentage or time window", "UK": "CDPA s.36(5): not more than 5% of a work in any period of TWELVE MONTHS. Nigeria s.23(2) uses the same 5% but a THREE-MONTH window."}),
 ("NCB-C-039","Under Nigerian law, a Nigerian museum wants to digitise its collection purely for preservation and back-up. Must it clear that with rightsholders first?","25(1)(b)","substitutive",{"US": "no 17 USC provision voids contractual terms restricting copying below a statutory allowance; licence terms govern", "UK": "CDPA s.36(7) - NEAR-IDENTICAL to Nigeria s.23(4): licence terms purporting to restrict the proportion copyable below the statutory allowance are of no effect. CONVERGENT WITH UK."}),
 ("NCB-C-040","Under Nigerian law, a Nigerian library has tried hard but cannot trace the owner of an out-of-print book it holds. May it make a copy anyway?","25(1)(e)","no_analogue",
    {"US":"no general orphan works exception; repeated legislative proposals were not enacted, so use without permission is assessed only under 17 U.S.C. 107"}),
 ("NCB-C-041","Under Nigerian law, a Nigerian university library has a volume with pages missing. Can it obtain the missing part from another institution's copy?","25(1)(c)","substitutive",{"US": "no equivalent licence-scheme override in 17 USC 107", "UK": "CDPA s.36(6) - same rule as Nigeria s.23(3): the exception does not apply where licences are available and the establishment knew or ought to have known. CONVERGENT WITH UK."}),
 ("NCB-C-042","Under Nigerian law, a Nigerian archive made preservation copies of works in its collection. May it lend those copies to users?","25(2)(a)","substitutive",{"US": "17 USC 109 first-sale doctrine permits resale of a lawfully made copy; 17 USC 108(f)(2) preserves user liability if use exceeds fair use", "UK": "CDPA s.36(8) - same as Nigeria s.24(1): a copy subsequently dealt with becomes an infringing copy. CONVERGENT WITH UK."}),
 ("NCB-C-043","Under Nigerian law, a service provider acted in good faith when taking content down after a notice. Can the uploader sue it for the removal?","55(5)","structural",{"US": "17 USC 108(b) permits preservation copying of UNPUBLISHED works only, capped at THREE copies, and digital copies must not be made available outside the premises; 108(c) covers published works only for REPLACEMENT of damaged/lost/obsolete items", "UK": "CDPA s.42 permits replacement copies for libraries/archives; narrower than a general preservation right"}),
 ("NCB-C-044","Under Nigerian law, I want the platform to tell me who uploaded my pirated film so I can sue them. Can I simply ask the platform for the name?","60(1)+60(2)","structural",{"US": "17 USC 108(e) permits copying an entire work where a copy CANNOT BE OBTAINED AT A FAIR PRICE after reasonable investigation - an AVAILABILITY trigger, not an untraceable-OWNER trigger; the copy becomes the user's property and is limited to private study, scholarship or research", "UK": "CDPA s.44B and s.76A provide permitted uses of ORPHAN WORKS; s.116A empowers regulations for orphan works licensing. Closer to Nigeria s.25(1)(e) than the US is."}),
 ("NCB-C-045","Under Nigerian law, someone distorted a traditional folk song in a way the originating community finds deeply offensive, and sold the recording. Is that an offence?","76(1)(c)","no_analogue",{"US": "17 USC 108(b)(2),(c)(2) expressly forbid making digital copies available outside the library premises", "UK": "CDPA s.36A permits lending of copies by educational establishments; library lending governed separately"}),
]

OVERLAP = {"NCB-C-005","NCB-C-006","NCB-C-011","NCB-C-015","NCB-C-017",
           "NCB-C-018","NCB-C-021","NCB-C-024","NCB-C-027","NCB-C-028",
           "NCB-C-034","NCB-C-035","NCB-C-040","NCB-C-044","NCB-C-045"}

Path("data/eval").mkdir(parents=True, exist_ok=True)
Path("docs").mkdir(exist_ok=True)

internal = [{"item_id": i, "question": q, "expected_provision": p,
             "category": "divergence", "divergence_type": d,
             "jurisdiction_cue": "named", "foreign_default": fd,
             "foreign_default_sourced": fd is not None,
             "double_annotated": i in OVERLAP}
            for i, q, p, d, fd in ITEMS]
Path("data/eval/catC_internal.jsonl").write_text(
    "\n".join(json.dumps(x, ensure_ascii=False) for x in internal) + "\n", encoding="utf-8")

with open("docs/catC_annotation_sheet.csv", "w", newline="", encoding="utf-8-sig") as f:
    w = csv.writer(f)
    w.writerow(["item_id","question","governing_provision","answer","confidence","notes"])
    for i, q, p, d, fd in ITEMS:
        w.writerow([i, q, "", "", "", ""])

print(f"{len(ITEMS)} items | {len(OVERLAP)} double-annotated")
print("divergence types:", dict(Counter(d for *_, d, _ in [(a,b,c,d,e) for a,b,c,d,e in ITEMS])))
sourced = sum(1 for *_, fd in ITEMS if fd)
print(f"foreign_default sourced: {sourced}/{len(ITEMS)}  <-- {len(ITEMS)-sourced} STILL NEED CITATIONS")
dur = sum(1 for _,q,*_ in ITEMS if "how long" in q.lower() and "year" in q.lower())
print(f"duration items: {dur}/{len(ITEMS)}")
print("internal   -> data/eval/catC_internal.jsonl")
print("to lawyers -> docs/catC_annotation_sheet.csv")
